import { Campaign, ContentSource } from "./types"

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Summer Product Launch",
    status: "active",
    createdAt: "2024-01-15",
  },
  {
    id: "camp-2",
    name: "Holiday Marketing Campaign",
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: "camp-3",
    name: "Brand Awareness Q1",
    status: "paused",
    createdAt: "2024-01-05",
  },
  {
    id: "camp-4",
    name: "Social Media Boost",
    status: "active",
    createdAt: "2024-01-20",
  },
  {
    id: "camp-5",
    name: "Product Demo Series",
    status: "completed",
    createdAt: "2023-12-28",
  },
  {
    id: "camp-6",
    name: "Influencer Collaboration",
    status: "active",
    createdAt: "2024-01-18",
  },
  {
    id: "camp-7",
    name: "Customer Testimonials",
    status: "active",
    createdAt: "2024-01-12",
  },
  {
    id: "camp-8",
    name: "Tutorial Series",
    status: "paused",
    createdAt: "2024-01-08",
  },
]

export const demoContentSources: ContentSource[] = [
  {
    id: "source-1",
    name: "Instagram Stories Source",
    aspectRatio: "9:16",
    orientation: "vertical",
    schedulerEnabled: true,
    campaigns: [demoCampaigns[0], demoCampaigns[1], demoCampaigns[3]],
    totalVideos: 1247,
    createdAt: "2024-01-15",
  },
  {
    id: "source-2",
    name: "YouTube Shorts Source",
    aspectRatio: "9:16",
    orientation: "vertical",
    schedulerEnabled: true,
    campaigns: [demoCampaigns[2], demoCampaigns[4]],
    totalVideos: 892,
    createdAt: "2024-01-10",
  },
  {
    id: "source-3",
    name: "Facebook Feed Source",
    aspectRatio: "16:9",
    orientation: "landscape",
    schedulerEnabled: false,
    campaigns: [demoCampaigns[5], demoCampaigns[6]],
    totalVideos: 2156,
    createdAt: "2024-01-12",
  },
  {
    id: "source-4",
    name: "TikTok Vertical Source",
    aspectRatio: "9:16",
    orientation: "vertical",
    schedulerEnabled: true,
    campaigns: [demoCampaigns[0], demoCampaigns[3], demoCampaigns[6], demoCampaigns[7]],
    totalVideos: 3421,
    createdAt: "2024-01-08",
  },
  {
    id: "source-5",
    name: "LinkedIn Landscape Source",
    aspectRatio: "16:9",
    orientation: "landscape",
    schedulerEnabled: false,
    campaigns: [demoCampaigns[1], demoCampaigns[2]],
    totalVideos: 678,
    createdAt: "2024-01-05",
  },
  {
    id: "source-6",
    name: "Twitter Video Source",
    aspectRatio: "16:9",
    orientation: "landscape",
    schedulerEnabled: true,
    campaigns: [demoCampaigns[4]],
    totalVideos: 445,
    createdAt: "2024-01-18",
  },
]
