import { TopicToVideo } from "./types"

export const demoTopicToVideos: TopicToVideo[] = [
  {
    id: "topic-1",
    name: "Summer Product Launch",
    topic: "Introducing our new summer collection with innovative features",
    aspectRatio: "9:16",
    orientation: "vertical",
    status: "completed",
    videosGenerated: 12,
    createdAt: "2024-01-15",
    schedulerEnabled: true,
    categories: ["Marketing"],
  },
  {
    id: "topic-2",
    name: "Tech Innovation 2024",
    topic: "Latest technology trends and innovations in 2024",
    aspectRatio: "16:9",
    orientation: "landscape",
    status: "processing",
    videosGenerated: 8,
    createdAt: "2024-01-10",
    schedulerEnabled: false,
    categories: ["Technology", "Education"],
  },
  {
    id: "topic-3",
    name: "Health & Wellness Tips",
    topic: "Daily health and wellness tips for a better lifestyle",
    aspectRatio: "9:16",
    orientation: "vertical",
    status: "completed",
    videosGenerated: 24,
    createdAt: "2024-01-12",
    schedulerEnabled: true,
    categories: ["Education"],
  },
  {
    id: "topic-4",
    name: "Cooking Recipes Series",
    topic: "Quick and easy cooking recipes for busy professionals",
    aspectRatio: "16:9",
    orientation: "landscape",
    status: "draft",
    videosGenerated: 0,
    createdAt: "2024-01-08",
    schedulerEnabled: false,
    categories: ["Entertainment"],
  },
  {
    id: "topic-5",
    name: "Travel Destinations",
    topic: "Top travel destinations to visit in 2024",
    aspectRatio: "9:16",
    orientation: "vertical",
    status: "completed",
    videosGenerated: 18,
    createdAt: "2024-01-05",
    schedulerEnabled: true,
    categories: ["Entertainment", "Marketing"],
  },
  {
    id: "topic-6",
    name: "Fitness Workout Guide",
    topic: "Home workout routines for fitness enthusiasts",
    aspectRatio: "16:9",
    orientation: "landscape",
    status: "failed",
    videosGenerated: 0,
    createdAt: "2024-01-18",
    schedulerEnabled: false,
    categories: ["Education"],
  },
]
