import type { GeneratedVideo, TopicToVideo } from "./types"

// Demo topic data
export const demoTopic: TopicToVideo = {
  id: "topic-1",
  name: "Summer Product Launch",
  topic: "Introducing our new summer collection with innovative features",
  aspectRatio: "9:16",
  orientation: "vertical",
  status: "completed",
  videosGenerated: 12,
  createdAt: "2024-01-15",
}

// Demo generated videos
export const demoGeneratedVideos: GeneratedVideo[] = [
  {
    id: "video-1",
    title: "Summer Collection Introduction",
    description: "Discover our latest summer collection featuring innovative designs and premium materials.",
    hashtags: "#SummerCollection #Fashion #NewArrivals #Style",
    videoUrl: "https://n8n-flow.blr1.cdn.digitaloceanspaces.com/shorts_automation/earth_in_motion/in_queue/ff2z9mu8b5h3bhdha26a3b3cc6cg427dg67g7426u3ba.mp4",
    thumbnailUrl: "https://via.placeholder.com/320x180",
    duration: "0:45",
    createdAt: "2024-01-20",
    status: "completed",
    schedulerEnabled: true,
    settings: {
      template: "Standard Video",
      videoType: "Song Type Video",
      transitions: "Fade, Zoom In",
      backgroundMusic: true,
      subtitles: true,
      voiceTts: true,
      footageLibrary: "Ambient, Upbeat",
      thumbnail: "Auto Generated",
    },
  },
  {
    id: "video-2",
    title: "Innovative Features Showcase",
    description: "Explore the cutting-edge features that make our summer collection stand out from the rest.",
    hashtags: "#Innovation #Features #Technology #Design",
    videoUrl: "https://n8n-flow.blr1.cdn.digitaloceanspaces.com/shorts_automation/earth_in_motion/in_queue/ff6pb4g8b5h3fe3a6h6a3b3ce492e24bbh285c7366bg.mp4",
    thumbnailUrl: "https://via.placeholder.com/320x180",
    duration: "1:20",
    createdAt: "2024-01-19",
    status: "completed",
    schedulerEnabled: false,
    settings: {
      template: "Short Form Video",
      videoType: "Standard Video",
      transitions: "Slide Right, Slide Left",
      backgroundMusic: true,
      subtitles: false,
      voiceTts: true,
      footageLibrary: "Cinematic",
      thumbnail: "Custom",
    },
  },
  {
    id: "video-3",
    title: "Premium Materials Overview",
    description: "Learn about the premium materials we use in our summer collection for ultimate comfort.",
    hashtags: "#PremiumMaterials #Quality #Comfort #Luxury",
    videoUrl: "https://n8n-flow.blr1.cdn.digitaloceanspaces.com/shorts_automation/earth_in_motion/in_queue/ffd35nm8b5h4cb5h63aa3b3bc9a6dedh68d2d66kwx9j.mp4",
    thumbnailUrl: "https://via.placeholder.com/320x180",
    duration: "0:55",
    createdAt: "2024-01-18",
    status: "completed",
    schedulerEnabled: true,
    settings: {
      template: "Tutorial Video",
      videoType: "Tutorial Video",
      transitions: "Cross Fade",
      backgroundMusic: false,
      subtitles: true,
      voiceTts: false,
      footageLibrary: "Calm",
      thumbnail: "Auto Generated",
    },
  },
  {
    id: "video-4",
    title: "Styling Tips and Ideas",
    description: "Get inspired with styling tips and ideas for our new summer collection pieces.",
    hashtags: "#StylingTips #FashionTips #OutfitIdeas #SummerStyle",
    createdAt: "2024-01-17",
    status: "processing",
    schedulerEnabled: false,
    settings: {
      template: "Promotional Video",
      videoType: "Promotional Video",
      transitions: "Wipe, Dissolve",
      backgroundMusic: true,
      subtitles: true,
      voiceTts: true,
      footageLibrary: "Energetic",
      thumbnail: "Custom",
    },
  },
  {
    id: "video-5",
    title: "Customer Testimonials",
    description: "Hear what our customers are saying about the new summer collection.",
    hashtags: "#Testimonials #Reviews #CustomerLove #Feedback",
    createdAt: "2024-01-16",
    status: "draft",
    schedulerEnabled: true,
    settings: {
      template: "Storytelling Video",
      videoType: "Standard Video",
      transitions: "Fade",
      backgroundMusic: true,
      subtitles: false,
      voiceTts: true,
      footageLibrary: "Ambient",
      thumbnail: "Auto Generated",
    },
  },
]

// Helper function to generate metadata from topic
export function generateVideoFromTopic(topic: TopicToVideo, settings?: GeneratedVideo["settings"]): GeneratedVideo {
  return {
    id: `video-${Date.now()}`,
    title: `${topic.name} - Generated Video`,
    description: `Automatically generated video based on: ${topic.topic}`,
    hashtags: "#Generated #Automated #Video",
    createdAt: new Date().toISOString().split("T")[0],
    status: "processing",
    settings: settings || {
      template: "Standard Video",
      videoType: "Standard Video",
      transitions: "Fade",
      backgroundMusic: false,
      subtitles: false,
      voiceTts: false,
      footageLibrary: "-",
      thumbnail: "Auto Generated",
    },
  }
}
